package com.amazonaws.mobile.api;

//
//  CloudLogicAPIFactory.java
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.15
//

/**
 * Produces instances of Cloud Logic API configuration.
 */
public class CloudLogicAPIFactory {

    private CloudLogicAPIFactory() {
    }

    /**
     * Gets the configured micro-service instances.
     *
     * @return
     */
    public static CloudLogicAPIConfiguration[] getAPIs() {
        final CloudLogicAPIConfiguration[] apis = new CloudLogicAPIConfiguration[]{
                new CloudLogicAPIConfiguration("Clothing-Commands",
                        "Clothing",
                        "https://ihgjlg4pg0.execute-api.us-east-1.amazonaws.com/Development",
                        new String[]{
                                "/items/123",
                        },
                        com.amazonaws.mobile.api.idihgjlg4pg0.ClothingCommandsMobileHubClient.class),
                new CloudLogicAPIConfiguration("Posting",
                        "Link S3 to noSQL",
                        "https://nkyaohbfi9.execute-api.us-east-1.amazonaws.com/Development",
                        new String[]{
                                "/items",
                                "/items/123",
                        },
                        com.amazonaws.mobile.api.idnkyaohbfi9.PostingMobileHubClient.class),
        };

        return apis;
    }
}
